/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MuseumsImport } from './routes/Museums'
import { Route as FooterImport } from './routes/Footer'
import { Route as ExhibitionsMetImport } from './routes/ExhibitionsMet'
import { Route as ExhibitionsHarvardImport } from './routes/ExhibitionsHarvard'
import { Route as ContactImport } from './routes/Contact'
import { Route as CollectionsImport } from './routes/Collections'
import { Route as AboutImport } from './routes/About'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as CollectionCollectionIdImport } from './routes/Collection/$collectionId'
import { Route as ExhibitionMuseumIdImport } from './routes/Exhibition/$museum/$id'

// Create/Update Routes

const MuseumsRoute = MuseumsImport.update({
  id: '/Museums',
  path: '/Museums',
  getParentRoute: () => rootRoute,
} as any)

const FooterRoute = FooterImport.update({
  id: '/Footer',
  path: '/Footer',
  getParentRoute: () => rootRoute,
} as any)

const ExhibitionsMetRoute = ExhibitionsMetImport.update({
  id: '/ExhibitionsMet',
  path: '/ExhibitionsMet',
  getParentRoute: () => rootRoute,
} as any)

const ExhibitionsHarvardRoute = ExhibitionsHarvardImport.update({
  id: '/ExhibitionsHarvard',
  path: '/ExhibitionsHarvard',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRoute,
} as any)

const CollectionsRoute = CollectionsImport.update({
  id: '/Collections',
  path: '/Collections',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const CollectionCollectionIdRoute = CollectionCollectionIdImport.update({
  id: '/Collection/$collectionId',
  path: '/Collection/$collectionId',
  getParentRoute: () => rootRoute,
} as any)

const ExhibitionMuseumIdRoute = ExhibitionMuseumIdImport.update({
  id: '/Exhibition/$museum/$id',
  path: '/Exhibition/$museum/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/Collections': {
      id: '/Collections'
      path: '/Collections'
      fullPath: '/Collections'
      preLoaderRoute: typeof CollectionsImport
      parentRoute: typeof rootRoute
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/ExhibitionsHarvard': {
      id: '/ExhibitionsHarvard'
      path: '/ExhibitionsHarvard'
      fullPath: '/ExhibitionsHarvard'
      preLoaderRoute: typeof ExhibitionsHarvardImport
      parentRoute: typeof rootRoute
    }
    '/ExhibitionsMet': {
      id: '/ExhibitionsMet'
      path: '/ExhibitionsMet'
      fullPath: '/ExhibitionsMet'
      preLoaderRoute: typeof ExhibitionsMetImport
      parentRoute: typeof rootRoute
    }
    '/Footer': {
      id: '/Footer'
      path: '/Footer'
      fullPath: '/Footer'
      preLoaderRoute: typeof FooterImport
      parentRoute: typeof rootRoute
    }
    '/Museums': {
      id: '/Museums'
      path: '/Museums'
      fullPath: '/Museums'
      preLoaderRoute: typeof MuseumsImport
      parentRoute: typeof rootRoute
    }
    '/Collection/$collectionId': {
      id: '/Collection/$collectionId'
      path: '/Collection/$collectionId'
      fullPath: '/Collection/$collectionId'
      preLoaderRoute: typeof CollectionCollectionIdImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/Exhibition/$museum/$id': {
      id: '/Exhibition/$museum/$id'
      path: '/Exhibition/$museum/$id'
      fullPath: '/Exhibition/$museum/$id'
      preLoaderRoute: typeof ExhibitionMuseumIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Collections': typeof CollectionsRoute
  '/Contact': typeof ContactRoute
  '/ExhibitionsHarvard': typeof ExhibitionsHarvardRoute
  '/ExhibitionsMet': typeof ExhibitionsMetRoute
  '/Footer': typeof FooterRoute
  '/Museums': typeof MuseumsRoute
  '/Collection/$collectionId': typeof CollectionCollectionIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/Exhibition/$museum/$id': typeof ExhibitionMuseumIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Collections': typeof CollectionsRoute
  '/Contact': typeof ContactRoute
  '/ExhibitionsHarvard': typeof ExhibitionsHarvardRoute
  '/ExhibitionsMet': typeof ExhibitionsMetRoute
  '/Footer': typeof FooterRoute
  '/Museums': typeof MuseumsRoute
  '/Collection/$collectionId': typeof CollectionCollectionIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/Exhibition/$museum/$id': typeof ExhibitionMuseumIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Collections': typeof CollectionsRoute
  '/Contact': typeof ContactRoute
  '/ExhibitionsHarvard': typeof ExhibitionsHarvardRoute
  '/ExhibitionsMet': typeof ExhibitionsMetRoute
  '/Footer': typeof FooterRoute
  '/Museums': typeof MuseumsRoute
  '/Collection/$collectionId': typeof CollectionCollectionIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/Exhibition/$museum/$id': typeof ExhibitionMuseumIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/About'
    | '/Collections'
    | '/Contact'
    | '/ExhibitionsHarvard'
    | '/ExhibitionsMet'
    | '/Footer'
    | '/Museums'
    | '/Collection/$collectionId'
    | '/demo/tanstack-query'
    | '/Exhibition/$museum/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/About'
    | '/Collections'
    | '/Contact'
    | '/ExhibitionsHarvard'
    | '/ExhibitionsMet'
    | '/Footer'
    | '/Museums'
    | '/Collection/$collectionId'
    | '/demo/tanstack-query'
    | '/Exhibition/$museum/$id'
  id:
    | '__root__'
    | '/'
    | '/About'
    | '/Collections'
    | '/Contact'
    | '/ExhibitionsHarvard'
    | '/ExhibitionsMet'
    | '/Footer'
    | '/Museums'
    | '/Collection/$collectionId'
    | '/demo/tanstack-query'
    | '/Exhibition/$museum/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  ExhibitionsHarvardRoute: typeof ExhibitionsHarvardRoute
  ExhibitionsMetRoute: typeof ExhibitionsMetRoute
  FooterRoute: typeof FooterRoute
  MuseumsRoute: typeof MuseumsRoute
  CollectionCollectionIdRoute: typeof CollectionCollectionIdRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ExhibitionMuseumIdRoute: typeof ExhibitionMuseumIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  ExhibitionsHarvardRoute: ExhibitionsHarvardRoute,
  ExhibitionsMetRoute: ExhibitionsMetRoute,
  FooterRoute: FooterRoute,
  MuseumsRoute: MuseumsRoute,
  CollectionCollectionIdRoute: CollectionCollectionIdRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ExhibitionMuseumIdRoute: ExhibitionMuseumIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/About",
        "/Collections",
        "/Contact",
        "/ExhibitionsHarvard",
        "/ExhibitionsMet",
        "/Footer",
        "/Museums",
        "/Collection/$collectionId",
        "/demo/tanstack-query",
        "/Exhibition/$museum/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/About": {
      "filePath": "About.tsx"
    },
    "/Collections": {
      "filePath": "Collections.tsx"
    },
    "/Contact": {
      "filePath": "Contact.tsx"
    },
    "/ExhibitionsHarvard": {
      "filePath": "ExhibitionsHarvard.tsx"
    },
    "/ExhibitionsMet": {
      "filePath": "ExhibitionsMet.tsx"
    },
    "/Footer": {
      "filePath": "Footer.tsx"
    },
    "/Museums": {
      "filePath": "Museums.tsx"
    },
    "/Collection/$collectionId": {
      "filePath": "Collection/$collectionId.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/Exhibition/$museum/$id": {
      "filePath": "Exhibition/$museum/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
